/*
 * SPDX-License-Identifier: Apache-2.0 AND GPL-3.0-only
 */

package com.best.deskclock.utils;

import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Utility methods shared by calendar-backed shift alarm synchronization. */
public final class ShiftAlarmUtils {

    /** Titles generated by GKUICalendar's shift assistant and compatible manual events. */
    public static final Pattern SHIFT_TITLE_PATTERN = Pattern.compile(
            "^(早班|中班|晚班|夜班|白班|Shift).*$", Pattern.CASE_INSENSITIVE);

    /** Legacy metadata generated by GKUICalendar, for example {@code Alarm: -90}. */
    public static final Pattern OFFSET_DESCRIPTION_PATTERN = Pattern.compile(
            "(?:^|\\r?\\n)\\s*Alarm:\\s*(-?\\d+)\\s*(?:$|\\r?\\n)",
            Pattern.CASE_INSENSITIVE);

    private static final Pattern STRUCTURED_OFFSET_PATTERN = Pattern.compile(
            "(?:^|\\r?\\n)\\s*X-GKUI-ALARM-OFFSET:\\s*(-?\\d+)\\s*(?:$|\\r?\\n)",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern STRUCTURED_SHIFT_PATTERN = Pattern.compile(
            "(?:^|\\r?\\n)\\s*X-GKUI-SHIFT(?:-ID)?:\\s*(.*?)\\s*(?:$|\\r?\\n)",
            Pattern.CASE_INSENSITIVE);
    private static final Pattern IGNORE_HOLIDAY_PATTERN = Pattern.compile(
            "(?:#IgnoreHoliday|X-GKUI-IGNORE-HOLIDAY:\\s*true)",
            Pattern.CASE_INSENSITIVE);

    public static final int DEFAULT_OFFSET_MINUTES = -90;
    public static final int MAX_ABSOLUTE_OFFSET_MINUTES = 7 * 24 * 60;
    public static final int CONFLICT_RESOLUTION_BUFFER_MINUTES = 30;
    public static final int SYNC_WINDOW_DAYS = 7;

    /** Optional device-wide fallback used by existing GKUI integrations. */
    public static final String SETTINGS_SECURE_SHIFT_ALARM_OFFSET =
            "deskclock_shift_alarm_offset";

    private ShiftAlarmUtils() {
    }

    public static boolean isShiftEvent(String title, String description) {
        if (title != null && SHIFT_TITLE_PATTERN.matcher(title.trim()).matches()) {
            return true;
        }
        return description != null && STRUCTURED_SHIFT_PATTERN.matcher(description).find();
    }

    public static int parseOffsetMinutes(String description, int fallbackMinutes) {
        Integer parsed = findInteger(STRUCTURED_OFFSET_PATTERN, description);
        if (parsed == null) {
            parsed = findInteger(OFFSET_DESCRIPTION_PATTERN, description);
        }
        return clampOffset(parsed == null ? fallbackMinutes : parsed);
    }

    public static boolean shouldIgnoreHoliday(String description) {
        return description != null && IGNORE_HOLIDAY_PATTERN.matcher(description).find();
    }

    /**
     * Builds a key that stays stable when a non-recurring event's start time changes. For recurring
     * events, the caller supplies an occurrence time (preferably ORIGINAL_INSTANCE_TIME) to
     * distinguish each generated occurrence.
     */
    public static String createSyncKey(long eventId, long occurrenceTime,
                                       String description) {
        final String structuredId = extractStructuredShiftId(description);
        final String occurrence = occurrenceTime > 0
                ? ":" + occurrenceTime
                : "";
        if (structuredId != null) {
            // Include the provider event id because a structured id may identify a reusable shift
            // preset rather than one concrete event occurrence.
            return "gkui:" + structuredId + ":" + eventId + occurrence;
        }
        return "calendar:" + eventId + occurrence;
    }

    private static Integer findInteger(Pattern pattern, String text) {
        if (text == null) {
            return null;
        }
        final Matcher matcher = pattern.matcher(text);
        if (!matcher.find()) {
            return null;
        }
        try {
            return Integer.parseInt(matcher.group(1));
        } catch (NumberFormatException ignored) {
            return null;
        }
    }

    private static int clampOffset(int minutes) {
        return Math.max(-MAX_ABSOLUTE_OFFSET_MINUTES,
                Math.min(MAX_ABSOLUTE_OFFSET_MINUTES, minutes));
    }

    private static String extractStructuredShiftId(String description) {
        if (description == null) {
            return null;
        }
        final Matcher matcher = STRUCTURED_SHIFT_PATTERN.matcher(description);
        if (!matcher.find()) {
            return null;
        }
        final String value = matcher.group(1) == null ? "" : matcher.group(1).trim();
        if (value.isEmpty() || "true".equals(value.toLowerCase(Locale.ROOT))) {
            return null;
        }
        // Keep database keys compact and prevent metadata line breaks from entering a key.
        return value.length() > 128 ? value.substring(0, 128) : value;
    }
}
