name: Android CI

on:
  # 1. 修改：让工作流也能在 holiday-alarm 分支上自动触发
  push:
    branches: [ "main", "holiday-alarm" ]
  pull_request:
    branches: [ "main", "holiday-alarm" ]
  
  # 2. 新增：添加这一段来允许手动触发工作流
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      # 增加 clean 命令可以防止一些缓存问题，是个好习惯
      run: ./gradlew clean build
